theme: jekyll-theme-minimal
sass:
  style: compressed
title: Levi Pulford
description: Portfolio
collections:
  samples:
    output: true
    permalink: /portfolio/:slug/
defaults:
  - scope:
      path: ""
      type: samples
    values:
      layout: sample
      section: portfolio
nav:
  - title: Home
    url: /
  - title: About Me
    url: /about.html
  - title: Resume
    url: /resume.html
  - title: Contact
    url: /contact.html

